[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
equisol = "EYkmzAxdQ6ivpuPJRQG25nwgp2aA6ZHLfv4iMz3fw72r"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts --skip-deploy"
